<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>SWT Report</title>
    <style>
        body {
            font-family: 'Helvetica', Arial, sans-serif;
            font-size: 12px;
            color: #1a1f36;
        }
        .header {
            background: linear-gradient(135deg, #1a1f36 0%, #2d3555 100%);
            padding: 20px 24px;
            border-radius: 10px;
            color: white;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 20px;
        }
        .header p {
            margin: 5px 0 0 0;
            opacity: 0.8;
        }
        .summary {
            display: flex;
            gap: 10px;
            margin-bottom: 20px;
        }
        .summary-card {
            flex: 1;
            background: #f8fafc;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 12px 16px;
            text-align: center;
        }
        .summary-card .label {
            font-size: 10px;
            color: #94a3b8;
            text-transform: uppercase;
        }
        .summary-card .value {
            font-size: 16px;
            font-weight: bold;
            color: #1a1f36;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        thead {
            background: #f1f5f9;
        }
        th {
            font-size: 10px;
            text-transform: uppercase;
            padding: 8px 12px;
            text-align: left;
            color: #475569;
        }
        td {
            padding: 8px 12px;
            border-bottom: 1px solid #f1f5f9;
            font-size: 11px;
        }
        tfoot {
            background: #f1f5f9;
            font-weight: bold;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            color: #94a3b8;
            text-align: center;
            border-top: 1px solid #e5e7eb;
            padding-top: 15px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>SWT Report</h1>
        <p>{{ $company->name }}</p>
        <p style="font-size: 12px;">Period: {{ $monthFormatted }}</p>
    </div>

    <div class="summary">
        <div class="summary-card">
            <div class="label">Total Employees</div>
            <div class="value">{{ $summary->total_employees }}</div>
        </div>
        <div class="summary-card">
            <div class="label">Total Gross Wages</div>
            <div class="value">K {{ number_format($summary->total_gross, 2) }}</div>
        </div>
        <div class="summary-card">
            <div class="label">Total Tax</div>
            <div class="value">K {{ number_format($summary->total_tax, 2) }}</div>
        </div>
        <div class="summary-card">
            <div class="label">Total Payroll Runs</div>
            <div class="value">{{ $summary->total_payrolls }}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Employee #</th>
                <th>Employee Name</th>
                <th style="text-align: right;">Gross Wages</th>
                <th style="text-align: right;">Tax</th>
                <th style="text-align: center;">Payrolls</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData as $index => $item)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $item->employee_number }}</td>
                    <td>{{ $item->full_name }}</td>
                    <td class="text-right">K {{ number_format($item->total_gross, 2) }}</td>
                    <td class="text-right">K {{ number_format($item->total_tax, 2) }}</td>
                    <td class="text-center">{{ $item->payroll_count }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" style="text-align: right;">TOTAL</td>
                <td class="text-right">K {{ number_format($summary->total_gross, 2) }}</td>
                <td class="text-right">K {{ number_format($summary->total_tax, 2) }}</td>
                <td class="text-center">{{ $summary->total_payrolls }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Generated: {{ now()->format('d M Y H:i:s') }} | Generated By: {{ auth()->user()->name ?? 'System' }}
    </div>
</body>
</html>